services:
  database:
    container_name: cda-${APP_NAME}-db
    image: postgres:14.2
    networks:
      - network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  main:
    container_name: cda-${APP_NAME}-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    command: > 
      sh -c "
             npm run db:create &&
             npm run db:seed &&
             npm run start:dev"
    env_file:
      - .env
    environment:
      DB_HOST: cda-${APP_NAME}-db
    networks:
      - network
    depends_on:
      - database
networks:
  network:
volumes:
  pgdata: