export enum CencoNavItemType {
  IconVariant = 'icon',
  TextVariant = 'text',
}

export enum CencoNavItemAlign {
  LeftVariant = 'left',
  RightVariant = 'right',
}

export type CencoNavItem = {
  align: CencoNavItemAlign;
  icon: string;
  id: number;
  label: string;
  order: number;
  reference: string;
  type: CencoNavItemType;
};

const paris: CencoNavItem[] = [
  {
    id: 1,
    order: 1,
    type: CencoNavItemType.TextVariant,
    label: 'Puntos Cencosud',
    reference: 'https://www.puntoscencosud.cl/puntos/',
    icon: '',
    align: CencoNavItemAlign.LeftVariant,
  },
  {
    id: 2,
    order: 2,
    type: CencoNavItemType.IconVariant,
    label: 'Easy',
    reference: 'https://www.easy.cl/',
    icon: '/icons/easy.svg',
    align: CencoNavItemAlign.LeftVariant,
  },
  {
    id: 3,
    order: 3,
    type: CencoNavItemType.IconVariant,
    label: 'Jumbo',
    reference: 'https://www.jumbo.cl/',
    icon: '/icons/jumbo.svg',
    align: CencoNavItemAlign.LeftVariant,
  },
  {
    id: 4,
    order: 4,
    type: CencoNavItemType.IconVariant,
    label: 'Santa Isabel',
    reference: 'https://www.santaisabel.cl/',
    icon: '/icons/sisa.svg',
    align: CencoNavItemAlign.LeftVariant,
  },
  {
    id: 5,
    order: 5,
    type: CencoNavItemType.IconVariant,
    label: 'SPID',
    reference: 'https://spidchile.cl/',
    icon: '/icons/spid.svg',
    align: CencoNavItemAlign.LeftVariant,
  },
  {
    id: 6,
    order: 1,
    type: CencoNavItemType.TextVariant,
    label: 'Cencosud Scotiabank',
    reference: 'https://www.tarjetacencosud.cl/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 7,
    order: 2,
    type: CencoNavItemType.TextVariant,
    label: 'Estado del pedido',
    reference: 'https://www.paris.cl/mi-cuenta/mis-compras',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
];

const easy: CencoNavItem[] = [
  {
    id: 1,
    order: 1,
    type: CencoNavItemType.IconVariant,
    label: 'Paris',
    reference: 'https://www.paris.cl/',
    icon: '/icons/paris.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 2,
    order: 2,
    type: CencoNavItemType.IconVariant,
    label: 'Jumbo',
    reference: 'https://www.jumbo.cl/',
    icon: '/icons/jumbo.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 3,
    order: 3,
    type: CencoNavItemType.IconVariant,
    label: 'Santa Isabel',
    reference: 'https://www.santaisabel.cl/',
    icon: '/icons/sisa.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 4,
    order: 4,
    type: CencoNavItemType.TextVariant,
    label: 'Mundo Experto',
    reference: 'https://mundoexperto.cl/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 5,
    order: 5,
    type: CencoNavItemType.TextVariant,
    label: 'Puntos Cencosud',
    reference: 'https://www.puntoscencosud.cl/puntos/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 6,
    order: 6,
    type: CencoNavItemType.TextVariant,
    label: 'Tarjeta Cencosud',
    reference: 'https://www.tarjetacencosud.cl/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 7,
    order: 7,
    type: CencoNavItemType.TextVariant,
    label: 'Mis Compras',
    reference: 'https://ayuda.easy.cl/ayuda/transacciones',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 8,
    order: 8,
    type: CencoNavItemType.TextVariant,
    label: 'Tiendas',
    reference: 'https://www.easy.cl/tiendas',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
];

const jumbo: CencoNavItem[] = [
  {
    id: 1,
    order: 1,
    type: CencoNavItemType.IconVariant,
    label: 'Santa Isabel',
    reference: 'https://www.santaisabel.cl/',
    icon: '/icons/sisa.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 2,
    order: 2,
    type: CencoNavItemType.IconVariant,
    label: 'Paris',
    reference: 'https://paris.cl/',
    icon: '/icons/paris.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 3,
    order: 3,
    type: CencoNavItemType.IconVariant,
    label: 'Easy',
    reference: 'https://www.easy.cl/',
    icon: '/icons/easy.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 4,
    order: 4,
    type: CencoNavItemType.IconVariant,
    label: 'SPID',
    reference: 'https://spidchile.cl/',
    icon: '/icons/spid.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 5,
    order: 5,
    type: CencoNavItemType.TextVariant,
    label: 'Jumbo Prime',
    reference: 'https://ayuda.jumbo.cl/ayuda/jumbo-prime/que-es-jumbo-prime',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 6,
    order: 6,
    type: CencoNavItemType.TextVariant,
    label: 'Puntos Cencosud',
    reference: 'https://www.puntoscencosud.cl/puntos/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 7,
    order: 7,
    type: CencoNavItemType.TextVariant,
    label: 'Tarjeta Cencosud',
    reference: 'https://www.tarjetacencosud.cl/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 8,
    order: 8,
    type: CencoNavItemType.TextVariant,
    label: 'Estado del pedido',
    reference: 'https://www.jumbo.cl/mis-compras',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
];

const sisa: CencoNavItem[] = [
  {
    id: 1,
    order: 1,
    type: CencoNavItemType.IconVariant,
    label: 'Jumbo',
    reference: 'https://www.jumbo.cl/',
    icon: '/icons/jumbo.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 2,
    order: 2,
    type: CencoNavItemType.IconVariant,
    label: 'Paris',
    reference: 'https://paris.cl/',
    icon: '/icons/paris.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 3,
    order: 3,
    type: CencoNavItemType.IconVariant,
    label: 'Easy',
    reference: 'https://www.easy.cl/',
    icon: '/icons/easy.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 4,
    order: 4,
    type: CencoNavItemType.IconVariant,
    label: 'SPID',
    reference: 'https://spidchile.cl/',
    icon: '/icons/spid.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 5,
    order: 5,
    type: CencoNavItemType.TextVariant,
    label: 'Puntos Cencosud',
    reference: 'https://www.puntoscencosud.cl/puntos/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 6,
    order: 6,
    type: CencoNavItemType.TextVariant,
    label: 'Tarjeta Cencosud',
    reference: 'https://www.tarjetacencosud.cl/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 7,
    order: 7,
    type: CencoNavItemType.TextVariant,
    label: 'Estado del pedido',
    reference: 'https://www.santaisabel.cl/mis-compras',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
];

const spid: CencoNavItem[] = [
  {
    id: 1,
    order: 1,
    type: CencoNavItemType.IconVariant,
    label: 'Jumbo',
    reference: 'https://www.jumbo.cl/',
    icon: '/icons/jumbo.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 2,
    order: 2,
    type: CencoNavItemType.IconVariant,
    label: 'Paris',
    reference: 'https://paris.cl/',
    icon: '/icons/paris.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 3,
    order: 3,
    type: CencoNavItemType.IconVariant,
    label: 'Easy',
    reference: 'https://www.easy.cl/',
    icon: '/icons/easy.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 4,
    order: 4,
    type: CencoNavItemType.IconVariant,
    label: 'Santa Isabel',
    reference: 'https://www.santaisabel.cl/',
    icon: '/icons/sisa.svg',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 5,
    order: 5,
    type: CencoNavItemType.TextVariant,
    label: 'Puntos Cencosud',
    reference: 'https://www.puntoscencosud.cl/puntos/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 6,
    order: 6,
    type: CencoNavItemType.TextVariant,
    label: 'Tarjeta Cencosud',
    reference: 'https://www.tarjetacencosud.cl/',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
  {
    id: 7,
    order: 7,
    type: CencoNavItemType.TextVariant,
    label: 'Estado del pedido',
    reference: 'https://www.santaisabel.cl/mis-compras',
    icon: '',
    align: CencoNavItemAlign.RightVariant,
  },
];

const wong: CencoNavItem[] = [];

export const cencoNavByFlag: Record<string, CencoNavItem[]> = {
  paris,
  easy,
  jumbo,
  sisa,
  spid,
  wong,
};
